development:
  adapter: postgresql
  encoding: unicode
  database: wordsmith_development
  pool: 5
  username: capnsol
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wordsmith_test
  pool: 5
  username: capnsol
  password:
  